# Generated by Django 5.2.1 on 2025-05-14 18:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('first_surname', models.CharField(max_length=30)),
                ('second_surname', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('sanctions', models.IntegerField(default=0)),
                ('sanction_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publication_year', models.IntegerField()),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('stock', models.IntegerField(default=1)),
                ('available', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_biblioteca.category')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_biblioteca.editorial')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_biblioteca.language')),
            ],
        ),
        migrations.CreateModel(
            name='Lending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.SmallIntegerField(choices=[(0, 'Prestado'), (1, 'Devuelto'), (2, 'Atrasado')], default=0)),
                ('loan_term_days', models.IntegerField(default=7)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=1.5, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('estimated_return_date', models.DateField()),
                ('real_return_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_biblioteca.book')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_biblioteca.reader')),
            ],
        ),
    ]
