# Generated by Django 5.2.1 on 2025-05-14 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Genre',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='category',
            new_name='genre',
        ),
    ]
