# Generated by Django 5.2 on 2025-05-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_biblioteca', '0003_lending_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lending',
            name='user',
        ),
        migrations.AddField(
            model_name='reader',
            name='pin',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
