# Generated by Django 5.2.1 on 2025-05-22 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_biblioteca', '0003_lending_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lending',
            name='user',
        ),
    ]
